export { categoryRouter } from './category.controller'
export { productRouter } from './product.controller'
export { uploadRouter } from './upload.controller'
export { orderRouter } from './order.controller'
export { paymentRouter } from './payment.controller'
export { authRouter } from './auth.controller'